version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: 'postgres'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edges
    ports:
      - '5433:5432'
  rabbitmq:
    image: rabbitmq:latest
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge